Repository robo-bootcamp/pyBotic, pull requests merged in 2020-06, with the labels that each got.

#10 Feature/geomerty
  .github/workflows/python-package.yml
  README.md
  pybotic/__init__.py
  pybotic/geometry.py
  pybotic/worlds.py
  requirements.txt
  tests/test_geometry.py
Labels: feature

#4 Fixes #8 - Feature/world
  .github/workflows/python-package.yml
  .gitignore
  pybotic/__init__.py
  pybotic/geometry.py
  pybotic/utils/__init__.py
  pybotic/utils/world_utils.py
  pybotic/world/__init__.py
  pybotic/world/world.py
  pybotic/worlds.py
  requirements.txt
  setup.py
  tests/dummy_test.py
  tests/sample_world.txt
  tests/test_Continous3D_Static.py
  tests/test_geometry.py
  tests/test_utils.py
Labels: feature

#11 Closes #5 - Feature/map loader
  .github/workflows/python-package.yml
  pybotic/utils/__init__.py
  pybotic/utils/world_utils.py
  pybotic/worlds.py
  tests/sample_world.txt
  tests/test_utils.py
Labels: feature

#15 Feature/code factor
  .github/workflows/main.yml
  .github/workflows/python-package.yml
  README.md
  pybotic/geometry.py
  pybotic/worlds.py
  tests/test_utils.py
Labels: best practices

#19 Closes #20 - Feature/type hinting
  .github/workflows/python-package.yml
  pybotic/geometry.py
  pybotic/utils/world_utils.py
  pybotic/worlds.py
  setup.py
  tests/test_Continous3D_Static.py
  tests/test_geometry.py
  tests/test_world_utils.py
Labels: best practices, feature
